### ISSUE TITLE
Main Slider Arrows on Mobile

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#175] opened 2018-04-09 21:32 UTC
Please note that always showing the arrows on the main slider on mobile, ruins the entire look of the slider.
We already have the dots underneath the slider, that help us navigate between slides, so in my opinion the arrows should be hidden/removed on mobile.
It would look cleaner and more professional.

![screenshot_20180410-001934](https://user-images.githubusercontent.com/3336728/38523978-c0256bce-3c55-11e8-9ba1-cd4904b9fa4f.png)

**Comment by villagedefrance** [comment] 2018-04-11 12:29
Arrows can be switched off in the Slideshow module Settings.
However, if enabled, they will show on mobile as you describe.
I have looked into the FlexSlider options again and an "hide arrows on mobile" option does not exist as far as I can tell, only the "Touch" option does but that doesn't affect the arrows. So I am afraid I can't do much about this.
I think this issue should be closed as it is not a bug and not much can be done about it.

**Comment by Tangol** [comment] 2018-04-11 12:58
No problem, it was more of a styling quirk.
Can be closed.

Thanks!

**Closed** 2018-04-12 14:17 UTC
