### ISSUE TITLE
Catalog Mobile Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#181] opened 2018-05-12 08:38 UTC
Please note that when viewing a product on mobile, you can horizontally scroll the middle portion page.

![screenshot_20180512-104253](https://user-images.githubusercontent.com/3336728/39955521-cbcf7748-55d8-11e8-8c2e-41dc9823636c.png)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/ce557dbfc056ef5110406ba3b3e73bc860ead282

**Comment by villagedefrance** [comment] 2018-05-13 08:59
How big is your product main image?
If the main image width is larger than the screen width, then yes, this will happen. Because the product image Thumb Size is set in Settings, it cannot be responsive.
Keeping the main image width below 300px (including CSS padding) should fix this.
So this is not a bug.
Again, for those who choose to display large images on their site have to realize that they assume that people will view the page on landscape mode, as portrait will obviously be overflowing.

**Comment by Tangol** [comment] 2018-05-13 10:48
The test was done on http://bench.villagedefrance.net/ , viewing the **HTC Touch HD**.
The image isn't larger than the screen, as everything shows up nicely, except for the horizontal scroll...

My screen is a 5.2", 1080 x 1920 pixels, 16:9 ratio and the **Product Image Thumb Size** is **230x230**, so I shouldn't be getting any horizontal scroll.

**Comment by villagedefrance** [comment] 2018-05-15 08:34
Ok, this is now fixed.
It took me a while to find the problem because all other products were fine, but I got it in the end.
The issue was with the product image label (right hand side label). The CSS was pushing to the right and almost doubling the size of the main image, creating the overflow.
Thank you for spotting this small yet important issue.

**Closed by villagedefrance** 2018-05-15 08:34 UTC
