### ISSUE TITLE
Admin search fields issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#163] opened 2018-03-22 18:03 UTC
Please note that when searching for stuff using the search fields in the **Admin**, you are limited to search only using the first keyword in a name.

For example, you have **iPod Touch** in the product list.
To find it, you have to search for **ipod**.
If you search for **touch**, it returns no results.

![keyword](https://user-images.githubusercontent.com/3336728/37789144-d306f1b6-2e0b-11e8-979d-52f8e98bffec.jpg)

This is a big issue when you have hundreds of products, as it makes the search ineffective.

PS: this issue affects all search fields in the Admin side.

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/c8a4525b99aeff444d31fe4610c2839004d60618

**Comment by villagedefrance** [comment] 2018-03-22 19:34
I have just added a new commit that gives the ability to search products using both product's name and/or  manufacturer's name as well.
Now this is as far as it can go because there are too many factors involved:
- multiple parameters (Name + Model + Price + Quantity + Status);
- multi-languages;
- auto-complete;
- pagination;
- sorting (ASC or DESC)
The search is performed through an SQL query that changes depending on the parameters entered in the Filter. Pushing this too far could be trouble as the function is already 60 lines long, not including the "total" function to match the main function.

I don't think I can make more improvement on this.
I think the issue should now be closed as it is working as intended.

**Comment by Tangol** [comment] 2018-03-22 19:42
It still doesn't work.
You can only search either using the first keyword in a product's name, or the full name.

- If you have **HTC Touch**, and want to find it using the search, you have to insert HTC or HTC Touch.
If you only enter **touch**, you don't get any results.

![keyword](https://user-images.githubusercontent.com/3336728/37793957-c2b32b10-2e18-11e8-892d-4018bf432cc0.jpg)

- Another example at **Palettes**.

![palette](https://user-images.githubusercontent.com/3336728/37794295-c6c6b6bc-2e19-11e8-8b98-80d280fac6e8.jpg)

See what I mean?

**Comment by villagedefrance** [comment] 2018-03-22 19:50
I do understand.
... but like I said there are too many factors involved and I honestly **cannot** make this better!
I am open to suggestions, code snippets or PRs, if anybody can answer this. I can't. Sorry.

**Comment by Tangol** [comment] 2018-03-22 19:54
Oh ok, no problem.
I thought this was a bug that would have had an easy solution.

Thanks!

**Comment by Tangol** [comment] 2018-03-25 18:53
> I do understand.
> ... but like I said there are too many factors involved and I honestly cannot make this better!
> I am open to suggestions, code snippets or PRs, if anybody can answer this. I can't. Sorry.

Before we close it, some more thoughts regarding this matter.
As we already have a functional full text search system implemented in the front end, why can't it be ported to the **Admin** side also?

I mean, it basically does the same thing, right?
Query the database and return the results.

![search](https://user-images.githubusercontent.com/3336728/37878774-be2dfcae-3076-11e8-9357-412296c75701.jpg)

I know, I'm annoyingly stubborn! 😁

**Comment by villagedefrance** [comment] 2018-03-26 06:04
No, this is not the same thing at all!

The Admin product search (by name) is part of the **Product List Table**, which happens to have a Filter to limit the results based on Product options like name, model, price, and so on ...

The Front End search is on the other hand a **Global Search** with its dedicated controller, language files and result page. This searches the database for matches globally, including product name, category name, product descriptions, tag names, model, and now also colors. If you look at the examples (1,2,3) you kindly provided the name of the files are called "global_search".

These are 2 very different things!

Now the only way to achieve what you are asking would be to create a entirely new set of files (controller, language, model, template) under Admin called "Search" (or "Product Search"), which is possible.
But, let think about the consequences of doing that: This would mean offering 2 distinct ways of finding and editing products, the classic way (like at present) or the search way. The question is then how confusing this would be for the users, would it be a useful positive addition or a redundant negative solution?

I am happy to create this if we agree that it will be beneficial for the users, but I'm not sure it is really necessary as it would mean double the amount of code for pretty much the same result.

One thing is certain, these 2 ways cannot be merged into the same files. They have to be distinct.

**Comment by Tangol** [comment] 2018-03-26 06:52
I finally get it.
Thanks for the detailed response.

In this case, there's no need to bother with this anymore.

The only beneficial thing here, would be to add a **Global Search** in the admin (as per my old suggestion [here](https://github.com/villagedefrance/OpenCart-Overclocked/issues/96)).
That would greatly improve the Admin workflow, by adding the ability to instantly search for everything.

But then again, this isn't that urgent.

**Comment by Tangol** [comment] 2018-04-01 16:03
I guess this report can be closed, as it may get fixed in a future update, by adding the **Admin Global Search**.

Thanks!

**Closed** 2018-04-01 16:08 UTC
